// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using suivie_des_drones.Cores.Infrastructure.Database;

#nullable disable

namespace suivi_des_drones.Core.Infrastructure.Migrations
{
    [DbContext(typeof(DroneDbContext))]
    [Migration("20230920100304_ajoutIncident")]
    partial class ajoutIncident
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("suivi_des_drones.Core.Models.Drone", b =>
                {
                    b.Property<string>("Matricule")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("Matricule");

                    b.HasIndex("StatusId");

                    b.ToTable("Drone", (string)null);
                });

            modelBuilder.Entity("suivi_des_drones.Core.Models.HealthStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HealthStatus", (string)null);
                });

            modelBuilder.Entity("suivi_des_drones.Core.Models.Incident", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:Identity", "1, 1");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateIncident")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdDrone")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("PathFichier")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Raison")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("IdDrone")
                        .IsUnique();

                    b.ToTable("Incident", (string)null);
                });

            modelBuilder.Entity("suivi_des_drones.Core.Models.Login", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Login", (string)null);
                });

            modelBuilder.Entity("suivi_des_drones.Core.Models.Drone", b =>
                {
                    b.HasOne("suivi_des_drones.Core.Models.HealthStatus", "Status")
                        .WithMany("Drones")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Status");
                });

            modelBuilder.Entity("suivi_des_drones.Core.Models.Incident", b =>
                {
                    b.HasOne("suivi_des_drones.Core.Models.Drone", "IdDroneNav")
                        .WithOne("Probleme")
                        .HasForeignKey("suivi_des_drones.Core.Models.Incident", "IdDrone")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdDroneNav");
                });

            modelBuilder.Entity("suivi_des_drones.Core.Models.Drone", b =>
                {
                    b.Navigation("Probleme");
                });

            modelBuilder.Entity("suivi_des_drones.Core.Models.HealthStatus", b =>
                {
                    b.Navigation("Drones");
                });
#pragma warning restore 612, 618
        }
    }
}
